name: Deploy
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get Repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Run lint
        run: npm run lint
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get Repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Run test
        run: npm run test
  deploy:
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
      - name: Get Repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Run build
        run: npm run build
      - name: Run deploy
        run: echo "Deploying..."