name: Issues
on: issues
jobs:
  print-issue-details:
    runs-on: ubuntu-latest
    steps:
      - name: Print issue details
        run: echo "${{ toJSON(github.event.issue.title) }} - ${{ toJSON(github.event.action) }}"
